# -*- coding: utf-8 -*-
"""Assignment Day : 21

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E68Br6NaJxTWkqDLRPLuVyW7tGzwUF7R
"""

from collections import Counter
class MyCounter(Counter):
  def __call__(self,Counter):
    self.Counter=Counter
    print(Counter)
        
co1 = MyCounter()
co1("intel")