# -*- coding: utf-8 -*-
"""Assignment Day:5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QbsrpraEHpS5wL7UteB00ztuVWvgJfDA
"""

sheild = set()
messages = dict()
total = set()

for  each in range(10):
    sender, recv = input().split(":")
    sender, recv = sender.strip(),[i.strip() for i in recv.split(",")]
    message[sender] = recv
    total.add(sender)
    total = total.union(set(recv))

to_add = ["Nick Fury"]
while to_add:
    sender = to_add.pop(0)
    shield.add(sender)
    to_add.extend([ i for i in messages.get(sender,[])if i not in shield])
print(*sorted([*(total - shield)]),sep=', ')