# -*- coding: utf-8 -*-
"""ASSIGNMENT:01 Day:3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qMRweCGzh9qn3erSog_tN4cyX9M5VY2Y
"""

#using for loop print all the prime numbers between 1-200 using for loop and range function.


start = 2
end = 201
print("prime numbers are:")
  
for i in range(start,end): 
    for j in range(2,i): 
        if(i % j==0): 
            break
    else: 
        print(i)