# -*- coding: utf-8 -*-
"""Assignment Day :27

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umQGUxrgoU0nmqYdLBZ1t9GqG8Locu-Q
"""

import datetime
main_list = list(range(100000000))
list1=[]
t1 = datetime.datetime.now()
for each in main_list:
  (each**2)
  list1.append(each)
for each in list1:
   each
t2 = datetime.datetime.now()
print ("Using loop",t2-t1)

list2=[]
t3=datetime.datetime.now()
for i in main_list:
  i**2
  list2.append(i)
lis1 = iter(list2)
t4=datetime.datetime.now()

print ("Using iterator:",t4-t3)

list3=[]
t5 = datetime.datetime.now()
def PowTwoGen(max=100000000):
    n = 0
    while n < max:
        yield n ** 2
        n += 1
for b in PowTwoGen(max=100000000):
 b
t6 = datetime.datetime.now()
print("Using generator:",t6-t5)