# -*- coding: utf-8 -*-
"""Assignment Day : 16

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYBTj3I1E9nBDey92WUdI7cNGA3HlUOc
"""

import requests
import re
url="https://study-ccna.com/classes-of-ip-addresses/"
a=requests.get(url)
data_ip=a.text
ip=r"[0-9]+\.[0-9]+\.[0-9]+\.[0-9]"
list_ip=re.findall(ip,data_ip)
for each in list_ip:
  print(each)