# -*- coding: utf-8 -*-
"""ASSIGNMENT:2 DAY 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l29v5nxaIENRvyN05CtgVay3D0R0YjGf
"""

#You are a pilot, you want to land a plan safely,so WAP to take current altitude as a input and check wheather the altitude is less than 1000fts to land the plan, or more than 1000fts ,and if its less than 5000fts ask pilot to bring if down to 1000fts and if its more thsn 5000fts then ask pilot to turn around and attempt later.

print("PILOT : hello I'm 'ANJALI' please do guide me to land my plan")
print("GUIDER : Yes for sure,\nDo follow my instructions. The altitude required for landing plan is 1000fts\nPlease do enter your altitude.")
altitude=int(input("Enter ur altitude"))
if altitude<1000:
    print("Hey pilot'ANJALI' land your plan")
elif 1000<altitude<5000:
    print("Hey pilot 'ANJALI' come down to 1000 fts")
elif 5000<altitude:
    print("Hey pilot 'ANJALI'go around and try later")
else:
    print("enjoy the view")