# -*- coding: utf-8 -*-
"""Assignment Day:10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H-aYF66znMeU8Kq4_QEjZs5sAVxvP4TU
"""

#Convert 15-08-2020 15:20:20 into epoch time

import time
t1 = "15-08-2020 15:20:20"
def Hr_Ep(t1):
    t9 = time.strptime(t1,"%d-%m-%Y %H:%M:%S")
    t2 = time.mktime(t9)
    return t2
    
print(Hr_Ep(t1))

