# -*- coding: utf-8 -*-
"""DAY-05 Assignmentno.02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16QalAWYQR9Wayhvns4uCiJfV7TbDO2m3
"""

# Make a function for prime number and use filters to filter out all the prime numbers from 1-25000


lst = list(range(1,25000))
print(lst)
def checkPrime(num):
  
    for i in range (2,num):
      if num%i==0:
        return False
        break

      else:
        return True

checkPrime(17)

lst=list(range(25000))
print(lst)

lst_Prime=[]
for item in lst:
  if checkPrime(item):
    lst_Prime.append(item)
print(lst_Prime)

